@startuml Handy Mangement
skinparam style Strictuml

!theme plain


class HandyMangement {
   
}

class WorkerController {
   
}

class EntrepreneurController {
   
}

class EmployeeController {

}

class workerService{}
class workerRepo{}

class EmployeeService{}
class EmployeeRepo{}

class EntreprenuerService{}
class EntreprenuerRepo{}

database "HandyManagement Database"{
}


HandyMangement .. WorkerController
HandyMangement .. EntrepreneurController
HandyMangement .. EmployeeController


WorkerController ..> workerService
EntrepreneurController ..> EntreprenuerService
EmployeeController ..> EmployeeService


workerService .. workerRepo
EmployeeService .. EmployeeRepo
EntreprenuerService .. EntreprenuerRepo

workerRepo o-- Resume 
EntreprenuerRepo o--Worker 

EmployeeRepo o-- Appointment 
Appointment -- Worker

Resume --Worker

Worker -- "HandyManagement Database"
Appointment -- "HandyManagement Database"
Resume -- "HandyManagement Database"





@enduml