INSERT INTO WORKER(WORKER_ID,FIRST_NAME,LAST_NAME,JOB_TITLE) VALUES
(NULL,'Abishek','Humagain','Manager'),
(NULL,'Colin','Banger','Project Lead'),
(NULL,'Subin','Sebastrian','Worker'),
(NULL,'Linse','Mathew','Plumber'),
(NULL,'Dhruv','Jodha','Carpenter');

INSERT INTO APPOINTMENT(APPOINTMENT_ID, APPOINTMENT_DATE, WORKER_ID) VALUES
(   NULL, '08/17/20201', (SELECT WORKER_ID FROM WORKER WHERE FIRST_NAME='Abishek')),
(   NULL, '03/28/20201', (SELECT WORKER_ID FROM WORKER WHERE FIRST_NAME='Colin')),
(   NULL, '12/17/20201', (SELECT WORKER_ID FROM WORKER WHERE FIRST_NAME='Subin')),
(   NULL, '05/21/20201', (SELECT WORKER_ID FROM WORKER WHERE FIRST_NAME='Linse')),
(   NULL, '08/28/20201', (SELECT WORKER_ID FROM WORKER WHERE FIRST_NAME='Dhruv'));


INSERT INTO RESUMETABLE(RESUMETABLE_ID, PHONE, EMAILADDRESS, WORKER_ID) VALUES
(   NULL, '1234567891', 'abishek@gmail.com', (SELECT WORKER_ID FROM WORKER WHERE FIRST_NAME='Abishek')),
(   NULL, '1234567891', 'colin@gmail.com', (SELECT WORKER_ID FROM WORKER WHERE FIRST_NAME='Colin')),
(   NULL, '1234567891', 'subin@gmail.com', (SELECT WORKER_ID FROM WORKER WHERE FIRST_NAME='Subin')),
(   NULL, '1234567891', 'linse@gmail.com', (SELECT WORKER_ID FROM WORKER WHERE FIRST_NAME='Linse')),
(   NULL, '1234567891', 'dhruv@gmail.com', (SELECT WORKER_ID FROM WORKER WHERE FIRST_NAME='Dhruv'));

