DROP TABLE IF EXISTS HANDYMANAGEMENT;

DROP TABLE IF EXISTS EMPLOYEE;

CREATE TABLE EMPLOYEE;
(
    EMPLOYEE_ID INT PRIMARY KEY AUTO_INCREMENT,
    FIRST_NAME VARCHAR(30),
    LAST_NAME VARCHAR(25),
    JOB_TITLE VARCHAR(40),
    PAYRATE DECIMAL(6,2),
)
